apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: envoy-controller-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/<YOUR_ORG>/infra
    targetRevision: HEAD
    path: charts/envoy-gateway
    helm:
      valueFiles:
        - ../../values/dev/envoy-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: envoy-gateway
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
